<?php
use Drupal\custom_ajax_command\Form\CustomAjaxCommandForm;

function custom_ajax_command_preprocess_page (&$variables) {
 
  $variables['#attached']['library'][] = 'custom_ajax_command/custom_ajax_command';
 
  # Add libraries for anonymous
  $logged_in = \Drupal::currentUser()->isAuthenticated();
  if (! $logged_in) {
    $libraries['#attached']['library'][] = 'core/drupal.ajax';
  }
  render($libraries);
}

function custom_ajax_command_theme($existing, $type, $theme, $path) {
  return [
    'my_template' => [
      'variables' => ['test_var' => NULL],
    ],
    'my_template2' => [
      'variables' => ['test_var' => NULL],
    ],
    'my_template3' => [
      'variables' => [
        'test_var' => NULL,
        'ss_path' => NULL,
        'events' => [],
        'featured' => [],
      ]
    ],
    'ed_online' => [
      'variables' => [
        'ss_path' => NULL,
      ]
    ],
    'ed_online2' => [
      'variables' => [
        'ss_path' => NULL,
        'ss_path2' => NULL,
      ]
    ],
  ];
}

function custom_ajax_command_cron() {
  \Drupal::logger('custom_ajax_command')->notice('Cron ran for custom_ajax_command -apashnin');

}
